name: Visualisation de données avec python

on: # Déclencher le workflow à chaque push sur la branche main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test: # Construire et tester

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4 # Étape 1: Récupèrer mon code sur GitHub
      
    - name: Set up Python 3.10 # Étape 2: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies # Étape 3: Installer les librairies
      run: |
        pip install -r dependances.txt
       
        pip install jupyter
        
    - name: Run Python scripts and generate plots # Étape 4: EXÉCUTER MES SCRIPTS
      run: |
        # Exécuter tous mes scripts exemples pour générer les images
        python examples/example_1_iris_matplotlib.py
        python examples/example_2_iris_seaborn.py
        # Si j'ai un script principal, l'exécuter :
        # python src/main.py
        
    - name: List generated files #  Montrer que les images sont créées
      run: |
        ls -la assets/images/
        
    # - name: Upload plots as artifact #  Sauvegarder les images générées
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: visualization-assets
    #     path: assets/images/
